offensive_point_dict = {
	'Passing TD': 4,
	'25 Passing Yards': 1, # (+0.04PT/ per yard is awarded),
	'300+ Yard Passing Game': 3,
	'Interception': -1,
	'10 Rushing Yards': 1, # (+0.1PT per yard is awarded),
	'Rushing TD': 6,
	'100+ Yard Rushing Game': 3,
	'10 Receiving Yards': 1, # (+0.1PT per yard is awarded),
	'Reception': 1,
	'Receiving TD': 6,
	'100+ Yard Receiving Game': 3,
	'Punt/Kickoff Return/FG Return for TD': 6,
	'Fumble Lost': -1,
	'2 Point Conversion (Pass, Run, or Catch)': 2,
	'Offensive Fumble Recovery TD': 6,
}

defensive_point_dict = {
	'Sack': 1,
	'Interception': 2,
	'Fumble Recovery': 2,
	'Kickoff Return TD': 6,
	'Punt Return TD': 6,
	'FG Return TD': 6,
	'Interception Return TD': 6,
	'Fumble Recovery TD': 6,
	'Blocked Punt or FG Return TD': 6,
	'Safety': 2,
	'Blocked Kick': 2,
	'2 Point Conversion/ Extra-point Return': 2,
	'0 Points Allowed': 1,
	'1-6 Points Allowed': 7,
	'7-13 Points Allowed': 4,
	'14-20 Points Allowed': 1,
	'21-27 Points Allowed': 0,
	'28-34 Points Allowed': -1,
	'35+ Points Allowed': -4,
}

